parameters:
    ezsettings.default.content_edit.templates.edit: "EzSystemsRepositoryFormsBundle:Content:content_edit.html.twig"
    ezsettings.default.content_edit.templates.create: "EzSystemsRepositoryFormsBundle:Content:content_edit.html.twig"
    ezsettings.default.content_edit.templates.create_draft: "EzSystemsRepositoryFormsBundle:Content:content_create_draft.html.twig"
    ezsettings.default.user_edit.templates.update: "EzSystemsRepositoryFormsBundle:Content:content_edit.html.twig"
    ezsettings.default.user_edit.templates.create: "EzSystemsRepositoryFormsBundle:Content:content_edit.html.twig"
    ezsettings.default.limitation_value_templates:
        - { template: 'EzSystemsRepositoryFormsBundle::limitation_values.html.twig', priority: 0 }

    ezsettings.default.content_edit_view: {}
    ezsettings.default.content_create_view: {}
