ez_content_create_no_draft:
    path: /content/create/nodraft/{contentTypeIdentifier}/{language}/{parentLocationId}
    defaults:
        _controller: ez_content_edit:createWithoutDraftAction
    options:
        expose: true
    # @todo rename language to languageCode in 3.0

ez_content_draft_edit:
    path: /content/edit/draft/{contentId}/{versionNo}/{language}/{locationId}
    defaults:
        _controller: ez_content_edit:editVersionDraftAction
        language: ~ # @todo rename to languageCode in 3.0
        locationId: ~
    options:
        expose: true

ez_content_draft_create:
    path: /content/create/draft/{contentId}/{fromVersionNo}/{fromLanguage}/{toLanguage}
    defaults:
        _controller: ez_content_edit:createContentDraftAction
        contentId: null
        fromVersionNo: null
        fromLanguage: null
        toLanguage: null
    options:
        expose: true

ez_user_create:
    path: /user/create/{contentTypeIdentifier}/{language}/{parentLocationId}
    defaults:
        _controller: "ezrepoforms.controller.user:createAction"

ez_user_update:
    path: /user/update/{contentId}/{versionNo}/{language}
    defaults:
        _controller: "ezrepoforms.controller.user:editAction"
    options:
        expose: true

