ez_content_create_no_draft:
    path: /content/create/nodraft/{contentTypeIdentifier}/{language}/{parentLocationId}
    defaults:
        _controller: ez_content_edit:createWithoutDraftAction
    options:
        expose: true

ez_content_draft_edit:
    path: /content/edit/draft/{contentId}/{versionNo}/{language}
    defaults:
        _controller: ez_content_edit:editContentDraftAction
        language: null
    options:
        expose: true

ez_content_draft_create:
    path: /content/create/draft/{contentId}/{fromVersionNo}/{fromLanguage}/{toLanguage}
    defaults:
        _controller: ez_content_edit:createContentDraftAction
        contentId: null
        fromVersionNo: null
        fromLanguage: null
        toLanguage: null
    options:
        expose: true

ez_user_register:
  path: /register
  defaults:
      _controller: "ezrepoforms.controller.user_register:registerAction"

ez_user_register_confirmation:
  path: /register-confirm
  defaults:
      _controller: "ezrepoforms.controller.user_register:registerConfirmAction"
