ez_jsonschema_content_create_from_json_form:
    path: /content/create/nodraft/{contentTypeIdentifier}/{language}/{parentLocationId}.{_format}
    defaults:
        _controller: EzSystemsRepositoryFormsBundle:JsonSchema:createContentFromJson
    requirements:
        _format: json
    methods: [POST]

ez_jsonschema_content_create_form:
    path: /content/create/nodraft/{contentTypeIdentifier}/{language}/{parentLocationId}.{_format}
    defaults:
        _controller: EzSystemsRepositoryFormsBundle:JsonSchema:createContentForm
    requirements:
        _format: json

ez_content_create_no_draft:
    path: /content/create/nodraft/{contentTypeIdentifier}/{language}/{parentLocationId}
    defaults:
        _format: html
        _controller: ez_content_edit:createWithoutDraftAction
    requirements:
        _format: html

ez_user_register:
  path: /register
  defaults:
      _controller: "ezrepoforms.controller.user_register:registerAction"

ez_user_register_confirmation:
  path: /register-confirm
  defaults:
      _controller: "ezrepoforms.controller.user_register:registerConfirmAction"

