ezplatform.content.create_no_draft:
    path: /content/create/nodraft/{contentTypeIdentifier}/{language}/{parentLocationId}
    defaults:
        _controller: ez_content_edit:createWithoutDraftAction
    options:
        expose: true
    # @todo rename language to languageCode in 3.0

ezplatform.content.draft.edit:
    path: /content/edit/draft/{contentId}/{versionNo}/{language}/{locationId}
    defaults:
        _controller: ez_content_edit:editVersionDraftAction
        language: ~ # @todo rename to languageCode in 3.0
        locationId: ~
    options:
        expose: true

ezplatform.content.draft.create:
    path: /content/create/draft/{contentId}/{fromVersionNo}/{fromLanguage}
    defaults:
        _controller: ez_content_edit:createContentDraftAction
        contentId: ~
        fromVersionNo: ~
        fromLanguage: ~
    options:
        expose: true

ezplatform.user.create:
    path: /user/create/{contentTypeIdentifier}/{language}/{parentLocationId}
    defaults:
        _controller: "ezrepoforms.controller.user:createAction"

ezplatform.user.update:
    path: /user/update/{contentId}/{versionNo}/{language}
    defaults:
        _controller: "ezrepoforms.controller.user:editAction"
    options:
        expose: true

