imports:
    - {resource: language.yml}
    - {resource: section.yml}
    - {resource: role.yml}

parameters:
    ezrepoforms.field_type_form_mapper.registry.class: EzSystems\RepositoryForms\FieldType\FieldTypeFormMapperRegistry
    ezrepoforms.field_type_form_mapper.dispatcher.class: EzSystems\RepositoryForms\FieldType\FieldTypeFormMapperDispatcher
    ezrepoforms.content_type.create.form_type.class: EzSystems\RepositoryForms\Form\Type\ContentType\ContentTypeCreateType
    ezrepoforms.content_type.update.form_type.class: EzSystems\RepositoryForms\Form\Type\ContentType\ContentTypeUpdateType
    ezrepoforms.field_definition.form_type.class: EzSystems\RepositoryForms\Form\Type\FieldDefinition\FieldDefinitionType
    ezrepoforms.field.form_type.class: EzSystems\RepositoryForms\Form\Type\Content\ContentFieldType

    ezrepoforms.field_value.user_type.class: EzSystems\RepositoryForms\Form\Type\User\UserAccountType

    ezrepoforms.field_type.form_mapper.ezbinaryfile.class: EzSystems\RepositoryForms\FieldType\Mapper\BinaryFileFormMapper
    ezrepoforms.field_type.form_mapper.ezboolean.class: EzSystems\RepositoryForms\FieldType\Mapper\CheckboxFormMapper
    ezrepoforms.field_type.form_mapper.ezcountry.class: EzSystems\RepositoryForms\FieldType\Mapper\CountryFormMapper
    ezrepoforms.field_type.form_mapper.ezdate.class: EzSystems\RepositoryForms\FieldType\Mapper\DateFormMapper
    ezrepoforms.field_type.form_mapper.ezdatetime.class: EzSystems\RepositoryForms\FieldType\Mapper\DateTimeFormMapper
    ezrepoforms.field_type.form_mapper.ezfloat.class: EzSystems\RepositoryForms\FieldType\Mapper\FloatFormMapper
    ezrepoforms.field_type.form_mapper.ezimage.class: EzSystems\RepositoryForms\FieldType\Mapper\ImageFormMapper
    ezrepoforms.field_type.form_mapper.ezinteger.class: EzSystems\RepositoryForms\FieldType\Mapper\IntegerFormMapper
    ezrepoforms.field_type.form_mapper.ezisbn.class: EzSystems\RepositoryForms\FieldType\Mapper\ISBNFormMapper
    ezrepoforms.field_type.form_mapper.ezmedia.class: EzSystems\RepositoryForms\FieldType\Mapper\MediaFormMapper
    ezrepoforms.field_type.form_mapper.ezobjectrelation.class: EzSystems\RepositoryForms\FieldType\Mapper\RelationFormMapper
    ezrepoforms.field_type.form_mapper.ezobjectrelationlist.class: EzSystems\RepositoryForms\FieldType\Mapper\RelationListFormMapper
    ezrepoforms.field_type.form_mapper.ezpage.class: EzSystems\RepositoryForms\FieldType\Mapper\PageFormMapper
    ezrepoforms.field_type.form_mapper.ezrichtext.class: EzSystems\RepositoryForms\FieldType\Mapper\RichTextFormMapper
    ezrepoforms.field_type.form_mapper.ezselection.class: EzSystems\RepositoryForms\FieldType\Mapper\SelectionFormMapper
    ezrepoforms.field_type.form_mapper.ezstring.class: EzSystems\RepositoryForms\FieldType\Mapper\TextLineFormMapper
    ezrepoforms.field_type.form_mapper.eztext.class: EzSystems\RepositoryForms\FieldType\Mapper\TextBlockFormMapper
    ezrepoforms.field_type.form_mapper.eztime.class: EzSystems\RepositoryForms\FieldType\Mapper\TimeFormMapper
    ezrepoforms.field_type.form_mapper.form_type_based.class: EzSystems\RepositoryForms\FieldType\Mapper\FormTypeBasedFieldValueFormMapper
    ezrepoforms.field_type.form_mapper.ezuser.class: EzSystems\RepositoryForms\FieldType\Mapper\UserAccountFieldValueFormMapper

    ezrepoforms.validator.unique_content_type_identifier.class: EzSystems\RepositoryForms\Validator\Constraints\UniqueContentTypeIdentifierValidator
    ezrepoforms.validator.validator_configuration.class: EzSystems\RepositoryForms\Validator\Constraints\ValidatorConfigurationValidator
    ezrepoforms.validator.field_settings.class: EzSystems\RepositoryForms\Validator\Constraints\FieldSettingsValidator
    ezrepoforms.validator.default_field_value.class: EzSystems\RepositoryForms\Validator\Constraints\FieldDefinitionDefaultValueValidator
    ezrepoforms.validator.field_value.class: EzSystems\RepositoryForms\Validator\Constraints\FieldValueValidator

    ezrepoforms.twig.field_edit_rendering_extension.class: EzSystems\RepositoryForms\Twig\FieldEditRenderingExtension
    ezrepoforms.action_dispatcher.base.class: EzSystems\RepositoryForms\Form\ActionDispatcher\AbstractActionDispatcher
    ezrepoforms.action_dispatcher.content_type.class: EzSystems\RepositoryForms\Form\ActionDispatcher\ContentTypeDispatcher
    ezrepoforms.action_dispatcher.content_type.group.class: EzSystems\RepositoryForms\Form\ActionDispatcher\ContentTypeGroupDispatcher
    ezrepoforms.action_dispatcher.content.class: EzSystems\RepositoryForms\Form\ActionDispatcher\ContentDispatcher
    ezrepoforms.form_processor.content_type.class: EzSystems\RepositoryForms\Form\Processor\ContentTypeFormProcessor
    ezrepoforms.form_processor.content_type.options.redirect_route_after_publish: ~
    ezrepoforms.form_processor.content_type.options:
        redirectRouteAfterPublish: "%ezrepoforms.form_processor.content_type.options.redirect_route_after_publish%"
    ezrepoforms.form_processor.content_type_group.class: EzSystems\RepositoryForms\Form\Processor\ContentTypeGroupFormProcessor
    ezrepoforms.form_processor.content.class: EzSystems\RepositoryForms\Form\Processor\ContentFormProcessor
    ezrepoforms.form_processor.user_register.class: EzSystems\RepositoryForms\Form\Processor\UserRegisterFormProcessor

    ezrepoforms.controller.content_edit.class: EzSystems\RepositoryFormsBundle\Controller\ContentEditController
    ezrepoforms.controller.user_register.class: EzSystems\RepositoryFormsBundle\Controller\UserRegisterController

    ezrepoforms.user_register.registration_group_loader.configurable.class: EzSystems\RepositoryForms\UserRegister\ConfigurableRegistrationGroupLoader
    ezrepoforms.user_register.registration_content_type_loader.configurable.class: EzSystems\RepositoryForms\UserRegister\ConfigurableRegistrationContentTypeLoader
    ezrepoforms.user_register.view_templates_listener.class: EzSystems\RepositoryForms\EventListener\ViewTemplatesListener

    ezrepoforms.form_data_mapper.user_register.class: EzSystems\RepositoryForms\Data\Mapper\UserRegisterMapper

    ezrepoforms.user_content_type_identifier: "user"

services:
    # deprecated in 1.1, will be removed in 2.0
    ezrepoforms.field_type_form_mapper.registry:
        class: "%ezrepoforms.field_type_form_mapper.registry.class%"

    ezrepoforms.field_type_form_mapper.dispatcher:
        class: "%ezrepoforms.field_type_form_mapper.dispatcher.class%"

    ezrepoforms.content_type.create.form_type:
        class: "%ezrepoforms.content_type.create.form_type.class%"
        arguments: ["@ezpublish.api.service.content_type"]
        tags:
            - {name: form.type, alias: ezrepoforms_contenttype_create}

    ezrepoforms.content_type.update.form_type:
        class: "%ezrepoforms.content_type.update.form_type.class%"
        arguments: ["@ezpublish.field_type_collection.factory", "@translator"]
        tags:
            - {name: form.type, alias: ezrepoforms_contenttype_update}

    ezrepoforms.field_definition.form_type:
        class: "%ezrepoforms.field_definition.form_type.class%"
        arguments: ["@ezrepoforms.field_type_form_mapper.dispatcher", "@ezpublish.api.service.field_type"]
        calls:
            - [setGroupsList, ["@ezpublish.fields_groups.list"]]
        tags:
            - { name: form.type, alias: ezrepoforms_fielddefinition_update }

    ezrepoforms.field.form_type:
        class: "%ezrepoforms.field.form_type.class%"
        arguments: ["@ezrepoforms.field_type_form_mapper.dispatcher"]
        tags:
            - { name: form.type, alias: ezrepoforms_content_field }

    ezrepoforms.field_value.user_type:
        class: "%ezrepoforms.field_value.user_type.class%"
        tags:
            - { name: form.type, alias: ezuser }

    # FieldType form mappers
    ezrepoforms.field_type.form_mapper.ezbinaryfile:
        class: "%ezrepoforms.field_type.form_mapper.ezbinaryfile.class%"
        tags:
            - { name: ez.fieldFormMapper.definition, fieldType: ezbinaryfile }

    ezrepoforms.field_type.form_mapper.ezboolean:
        class: "%ezrepoforms.field_type.form_mapper.ezboolean.class%"
        tags:
            - { name: ez.fieldFormMapper.definition, fieldType: ezboolean }
            - { name: ez.fieldFormMapper.value, fieldType: ezboolean }
        arguments:
            - "@ezpublish.api.service.field_type"

    ezrepoforms.field_type.form_mapper.ezcountry:
        class: "%ezrepoforms.field_type.form_mapper.ezcountry.class%"
        arguments: ["%ezpublish.fieldType.ezcountry.data%"]
        tags:
            - { name: ez.fieldFormMapper.definition, fieldType: ezcountry }

    ezrepoforms.field_type.form_mapper.ezdate:
        class: "%ezrepoforms.field_type.form_mapper.ezdate.class%"
        tags:
            - { name: ez.fieldFormMapper.definition, fieldType: ezdate }

    ezrepoforms.field_type.form_mapper.ezdatetime:
        class: "%ezrepoforms.field_type.form_mapper.ezdatetime.class%"
        tags:
            - { name: ez.fieldFormMapper.definition, fieldType: ezdatetime }

    ezrepoforms.field_type.form_mapper.ezfloat:
        class: "%ezrepoforms.field_type.form_mapper.ezfloat.class%"
        arguments:
            - "@ezpublish.api.service.field_type"
        tags:
            - { name: ez.fieldFormMapper.definition, fieldType: ezfloat }

    ezrepoforms.field_type.form_mapper.ezimage:
        class: "%ezrepoforms.field_type.form_mapper.ezimage.class%"
        arguments:
            - "@ezpublish.api.service.field_type"
        tags:
            - { name: ez.fieldFormMapper.definition, fieldType: ezimage }

    ezrepoforms.field_type.form_mapper.ezinteger:
        class: "%ezrepoforms.field_type.form_mapper.ezinteger.class%"
        arguments:
            - "@ezpublish.api.service.field_type"
        tags:
            - { name: ez.fieldFormMapper.definition, fieldType: ezinteger }

    ezrepoforms.field_type.form_mapper.ezisbn:
        class: "%ezrepoforms.field_type.form_mapper.ezisbn.class%"
        arguments:
            - "@ezpublish.api.service.field_type"
        tags:
            - { name: ez.fieldFormMapper.definition, fieldType: ezisbn }

    ezrepoforms.field_type.form_mapper.ezmedia:
        class: "%ezrepoforms.field_type.form_mapper.ezmedia.class%"
        tags:
            - { name: ez.fieldFormMapper.definition, fieldType: ezmedia }

    ezrepoforms.field_type.form_mapper.ezobjectrelation:
        class: "%ezrepoforms.field_type.form_mapper.ezobjectrelation.class%"
        tags:
            - { name: ez.fieldFormMapper.definition, fieldType: ezobjectrelation }

    ezrepoforms.field_type.form_mapper.ezobjectrelationlist:
        class: "%ezrepoforms.field_type.form_mapper.ezobjectrelationlist.class%"
        arguments: ["@ezpublish.api.service.content_type", "@ezpublish.translation_helper"]
        tags:
            - { name: ez.fieldFormMapper.definition, fieldType: ezobjectrelationlist }

    ezrepoforms.field_type.form_mapper.ezpage:
        class: "%ezrepoforms.field_type.form_mapper.ezpage.class%"
        arguments: ["@ezpublish.fieldType.ezpage.pageService"]
        tags:
            - { name: ez.fieldFormMapper.definition, fieldType: ezpage }

    ezrepoforms.field_type.form_mapper.ezrichtext:
        class: "%ezrepoforms.field_type.form_mapper.ezrichtext.class%"
        tags:
            - { name: ez.fieldFormMapper.definition, fieldType: ezrichtext }

    ezrepoforms.field_type.form_mapper.ezselection:
        class: "%ezrepoforms.field_type.form_mapper.ezselection.class%"
        tags:
            - { name: ez.fieldFormMapper.definition, fieldType: ezselection }
            - { name: ez.fieldFormMapper.value, fieldType: ezselection }

    ezrepoforms.field_type.form_mapper.ezstring:
        class: "%ezrepoforms.field_type.form_mapper.ezstring.class%"
        tags:
            - { name: ez.fieldFormMapper.definition, fieldType: ezstring }
            - { name: ez.fieldFormMapper.value, fieldType: ezstring }
        arguments:
            - "@ezpublish.api.service.field_type"

    ezrepoforms.field_type.form_mapper.eztext:
        class: "%ezrepoforms.field_type.form_mapper.eztext.class%"
        tags:
            - { name: ez.fieldFormMapper.definition, fieldType: eztext }
            - { name: ez.fieldFormMapper.value, fieldType: eztext }
        arguments:
            - "@ezpublish.api.service.field_type"

    ezrepoforms.field_type.form_mapper.eztime:
        class: "%ezrepoforms.field_type.form_mapper.eztime.class%"
        tags:
            - { name: ez.fieldFormMapper.definition, fieldType: eztime }

    ezrepoforms.field_type.form_mapper.form_type_based:
        abstract: true
        class: "%ezrepoforms.field_type.form_mapper.form_type_based.class%"
        arguments:
            - "@ezpublish.api.service.field_type"

    ezrepoforms.field_type.form_mapper.ezuser:
        class: "%ezrepoforms.field_type.form_mapper.ezuser.class%"
        tags:
            - { name: ez.fieldFormMapper.value, fieldType: ezuser }
        arguments:
            - '@ezpublish.api.service.field_type'

    # Validators
    ezrepoforms.validator.unique_content_type_identifier:
        class: "%ezrepoforms.validator.unique_content_type_identifier.class%"
        arguments: ["@ezpublish.api.service.content_type"]
        tags:
            - { name: validator.constraint_validator, alias: ezrepoforms.validator.unique_content_type_identifier }

    ezrepoforms.validator.field_type.abstract:
        class: EzSystems\RepositoryForms\Validator\Constraints\FieldTypeValidator
        arguments: ["@ezpublish.api.service.field_type"]
        abstract: true

    ezrepoforms.validator.validator_configuration:
        parent: ezrepoforms.validator.field_type.abstract
        class: "%ezrepoforms.validator.validator_configuration.class%"
        tags:
            - { name: validator.constraint_validator, alias: ezrepoforms.validator.validator_configuration }

    ezrepoforms.validator.field_settings:
        parent: ezrepoforms.validator.field_type.abstract
        class: "%ezrepoforms.validator.field_settings.class%"
        tags:
            - { name: validator.constraint_validator, alias: ezrepoforms.validator.field_settings }

    ezrepoforms.validator.default_field_value:
        parent: ezrepoforms.validator.field_type.abstract
        class: "%ezrepoforms.validator.default_field_value.class%"
        tags:
            - { name: validator.constraint_validator, alias: ezrepoforms.validator.default_field_value }

    ezrepoforms.twig.field_edit_rendering_extension:
        class: "%ezrepoforms.twig.field_edit_rendering_extension.class%"
        arguments: ["@ezpublish.templating.field_block_renderer"]
        tags:
            - { name: twig.extension }

    ezrepoforms.validator.field_value:
        parent: ezrepoforms.validator.field_type.abstract
        class: "%ezrepoforms.validator.field_value.class%"
        tags:
            - { name: validator.constraint_validator, alias: ezrepoforms.validator.field_value }

    # Action dispatchers
    ezrepoforms.action_dispatcher.base:
        class: "%ezrepoforms.action_dispatcher.base.class%"
        abstract: true
        calls:
            - [setEventDispatcher, ["@event_dispatcher"]]

    ezrepoforms.action_dispatcher.content:
        class: "%ezrepoforms.action_dispatcher.content.class%"
        parent: ezrepoforms.action_dispatcher.base

    ezrepoforms.action_dispatcher.content_type:
        class: "%ezrepoforms.action_dispatcher.content_type.class%"
        parent: ezrepoforms.action_dispatcher.base

    ezrepoforms.action_dispatcher.content_type.group:
        class: "%ezrepoforms.action_dispatcher.content_type.group.class%"
        parent: ezrepoforms.action_dispatcher.base

    # Form processors
    ezrepoforms.form_processor.content_type:
        class: "%ezrepoforms.form_processor.content_type.class%"
        arguments: ["@ezpublish.api.service.content_type", "@router", "%ezrepoforms.form_processor.content_type.options%"]
        calls:
            - [setGroupsList, ["@ezpublish.fields_groups.list"]]
        tags:
            - { name: kernel.event_subscriber }

    ezrepoforms.form_processor.content:
        class: "%ezrepoforms.form_processor.content.class%"
        arguments: ["@ezpublish.api.service.content", "@router"]
        tags:
            - { name: kernel.event_subscriber }

    ezrepoforms.form_processor.user_register:
        class: "%ezrepoforms.form_processor.user_register.class%"
        arguments:
            - '@ezpublish.api.repository'
            - '@ezpublish.api.service.user'
            - '@router'
        tags:
            - { name: kernel.event_subscriber }

    ezrepoforms.form_processor.content_type_group:
        class: "%ezrepoforms.form_processor.content_type_group.class%"
        arguments: ["@ezpublish.api.service.content_type"]
        tags:
            - { name: kernel.event_subscriber }

    # Controllers
    ezrepoforms.controller.content_edit:
        class: "%ezrepoforms.controller.content_edit.class%"
        arguments:
            - "@ezpublish.api.service.content_type"
            - "@ezpublish.api.service.content"
            - "@ezpublish.api.service.location"
            - "@ezrepoforms.action_dispatcher.content"
        parent: ezpublish.controller.base
        calls:
            - [setPageLayout, [$pagelayout$]]

    ezrepoforms.controller.user_register:
        class: "%ezrepoforms.controller.user_register.class%"
        arguments:
            - "@ezrepoforms.form_data_mapper.user_register"
            - "@ezrepoforms.action_dispatcher.content"
        parent: ezpublish.controller.base

    ez_content_edit:
        alias: ezrepoforms.controller.content_edit

    ezrepoforms.user_register.registration_group_loader.configurable:
        class: "%ezrepoforms.user_register.registration_group_loader.configurable.class%"
        arguments:
            - "@ezpublish.api.repository"
        calls:
            - [setParam, ["groupId", "$user_registration.group_id$"]]

    ezrepoforms.user_register.registration_content_type_loader.configurable:
        class: "%ezrepoforms.user_register.registration_content_type_loader.configurable.class%"
        arguments:
            - "@ezpublish.api.repository"
        calls:
            - [setParam, ["contentTypeIdentifier", "%ezrepoforms.user_content_type_identifier%"]]

    ezrepoforms.form_data_mapper.user_register:
        class: "%ezrepoforms.form_data_mapper.user_register.class%"
        arguments:
            - "@ezrepoforms.user_register.registration_content_type_loader.configurable"
            - "@ezrepoforms.user_register.registration_group_loader.configurable"
        calls:
            - [setParam, ["language", "@=service('ezpublish.config.resolver').getParameter('languages', null, null)[0]"]]

    ezrepoforms.user_register.view_templates_listener:
        class: "%ezrepoforms.user_register.view_templates_listener.class%"
        tags:
            - { name: kernel.event_subscriber }
        calls:
            - [setViewTemplate, ['EzSystems\RepositoryForms\UserRegister\View\UserRegisterFormView', "$user_registration.templates.form$"]]
            - [setViewTemplate, ['EzSystems\RepositoryForms\UserRegister\View\UserRegisterConfirmView', "$user_registration.templates.confirmation$"]]
            - [setPagelayout, ["$pagelayout$"]]

    ezrepoforms.translation.extractor.sorting:
        class: EzSystems\RepositoryForms\Translation\SortingTranslationExtractor
        tags:
            - { name: jms_translation.extractor, alias: ez_location_sorting }
