parameters:
    ezrepoforms.field_type_form_mapper.registry.class: EzSystems\RepositoryForms\FieldType\FieldTypeFormMapperRegistry
    ezrepoforms.content_type.update.form_type.class: EzSystems\RepositoryForms\Form\Type\ContentTypeUpdateType
    ezrepoforms.field_definition.form_type.class: EzSystems\RepositoryForms\Form\Type\FieldDefinition\FieldDefinitionType

    ezrepoforms.field_type.form_mapper.ezbinaryfile.class: EzSystems\RepositoryForms\FieldType\Mapper\BinaryFileFormMapper
    ezrepoforms.field_type.form_mapper.ezcountry.class: EzSystems\RepositoryForms\FieldType\Mapper\CountryFormMapper
    ezrepoforms.field_type.form_mapper.ezdate.class: EzSystems\RepositoryForms\FieldType\Mapper\DateFormMapper
    ezrepoforms.field_type.form_mapper.ezfloat.class: EzSystems\RepositoryForms\FieldType\Mapper\FloatFormMapper
    ezrepoforms.field_type.form_mapper.ezinteger.class: EzSystems\RepositoryForms\FieldType\Mapper\IntegerFormMapper
    ezrepoforms.field_type.form_mapper.ezisbn.class: EzSystems\RepositoryForms\FieldType\Mapper\ISBNFormMapper
    ezrepoforms.field_type.form_mapper.ezmedia.class: EzSystems\RepositoryForms\FieldType\Mapper\MediaFormMapper
    ezrepoforms.field_type.form_mapper.ezpage.class: EzSystems\RepositoryForms\FieldType\Mapper\PageFormMapper
    ezrepoforms.field_type.form_mapper.ezselection.class: EzSystems\RepositoryForms\FieldType\Mapper\SelectionFormMapper
    ezrepoforms.field_type.form_mapper.ezstring.class: EzSystems\RepositoryForms\FieldType\Mapper\TextLineFormMapper
    ezrepoforms.field_type.form_mapper.eztext.class: EzSystems\RepositoryForms\FieldType\Mapper\TextBlockFormMapper
    ezrepoforms.field_type.form_mapper.eztime.class: EzSystems\RepositoryForms\FieldType\Mapper\TimeFormMapper

    ezrepoforms.validator.unique_content_type_identifier.class: EzSystems\RepositoryForms\Validator\Constraints\UniqueContentTypeIdentifierValidator
    ezrepoforms.validator.validator_configuration.class: EzSystems\RepositoryForms\Validator\Constraints\ValidatorConfigurationValidator
    ezrepoforms.validator.field_settings.class: EzSystems\RepositoryForms\Validator\Constraints\FieldSettingsValidator
    ezrepoforms.validator.default_field_value.class: EzSystems\RepositoryForms\Validator\Constraints\FieldDefinitionDefaultValueValidator

    ezrepoforms.twig.field_edit_rendering_extension.class: EzSystems\RepositoryForms\Twig\FieldEditRenderingExtension
    ezrepoforms.action_dispatcher.content_type.class: EzSystems\RepositoryForms\Form\ActionDispatcher\ContentTypeDispatcher
    ezrepoforms.form_processor.content_type.class: EzSystems\RepositoryForms\Form\Processor\ContentTypeFormProcessor
    ezrepoforms.form_processor.content_type.options.redirect_route_after_publish: ~
    ezrepoforms.form_processor.content_type.options:
        redirectRouteAfterPublish: %ezrepoforms.form_processor.content_type.options.redirect_route_after_publish%

services:
    ezrepoforms.field_type_form_mapper.registry:
        class: %ezrepoforms.field_type_form_mapper.registry.class%

    ezrepoforms.content_type.update.form_type:
        class: %ezrepoforms.content_type.update.form_type.class%
        arguments: [@ezpublish.field_type_collection.factory, @translator]
        tags:
            - {name: form.type, alias: ezrepoforms_contenttype_update}

    ezrepoforms.field_definition.form_type:
        class: %ezrepoforms.field_definition.form_type.class%
        arguments: [@ezrepoforms.field_type_form_mapper.registry, @ezpublish.api.service.field_type]
        tags:
            - { name: form.type, alias: ezrepoforms_fielddefinition_update }

    # FieldType form mappers
    ezrepoforms.field_type.form_mapper.ezbinaryfile:
        class: %ezrepoforms.field_type.form_mapper.ezbinaryfile.class%
        tags:
            - { name: ez.fieldType.formMapper, fieldType: ezbinaryfile }

    ezrepoforms.field_type.form_mapper.ezcountry:
        class: %ezrepoforms.field_type.form_mapper.ezcountry.class%
        arguments: [%ezpublish.fieldType.ezcountry.data%]
        tags:
            - { name: ez.fieldType.formMapper, fieldType: ezcountry }

    ezrepoforms.field_type.form_mapper.ezdate:
        class: %ezrepoforms.field_type.form_mapper.ezdate.class%
        tags:
            - { name: ez.fieldType.formMapper, fieldType: ezdate }

    ezrepoforms.field_type.form_mapper.ezfloat:
        class: %ezrepoforms.field_type.form_mapper.ezfloat.class%
        tags:
            - { name: ez.fieldType.formMapper, fieldType: ezfloat }

    ezrepoforms.field_type.form_mapper.ezinteger:
        class: %ezrepoforms.field_type.form_mapper.ezinteger.class%
        tags:
            - { name: ez.fieldType.formMapper, fieldType: ezinteger }

    ezrepoforms.field_type.form_mapper.ezisbn:
        class: %ezrepoforms.field_type.form_mapper.ezisbn.class%
        tags:
            - { name: ez.fieldType.formMapper, fieldType: ezisbn }

    ezrepoforms.field_type.form_mapper.ezmedia:
        class: %ezrepoforms.field_type.form_mapper.ezmedia.class%
        tags:
            - { name: ez.fieldType.formMapper, fieldType: ezmedia }

    ezrepoforms.field_type.form_mapper.ezpage:
        class: %ezrepoforms.field_type.form_mapper.ezpage.class%
        arguments: [@ezpublish.fieldType.ezpage.pageService]
        tags:
            - { name: ez.fieldType.formMapper, fieldType: ezpage }

    ezrepoforms.field_type.form_mapper.ezselection:
        class: %ezrepoforms.field_type.form_mapper.ezselection.class%
        tags:
            - { name: ez.fieldType.formMapper, fieldType: ezselection }

    ezrepoforms.field_type.form_mapper.ezstring:
        class: %ezrepoforms.field_type.form_mapper.ezstring.class%
        tags:
            - { name: ez.fieldType.formMapper, fieldType: ezstring }

    ezrepoforms.field_type.form_mapper.eztext:
        class: %ezrepoforms.field_type.form_mapper.eztext.class%
        tags:
            - { name: ez.fieldType.formMapper, fieldType: eztext }

    ezrepoforms.field_type.form_mapper.eztime:
        class: %ezrepoforms.field_type.form_mapper.eztime.class%
        tags:
            - { name: ez.fieldType.formMapper, fieldType: eztime }

    # Validators
    ezrepoforms.validator.unique_content_type_identifier:
        class: %ezrepoforms.validator.unique_content_type_identifier.class%
        arguments: [@ezpublish.api.service.content_type]
        tags:
            - { name: validator.constraint_validator, alias: ezrepoforms.validator.unique_content_type_identifier }

    ezrepoforms.validator.field_type.abstract:
        class: EzSystems\RepositoryForms\Validator\Constraints\FieldTypeValidator
        arguments: [@ezpublish.api.service.field_type]
        abstract: true

    ezrepoforms.validator.validator_configuration:
        parent: ezrepoforms.validator.field_type.abstract
        class: %ezrepoforms.validator.validator_configuration.class%
        tags:
            - { name: validator.constraint_validator, alias: ezrepoforms.validator.validator_configuration }

    ezrepoforms.validator.field_settings:
        parent: ezrepoforms.validator.field_type.abstract
        class: %ezrepoforms.validator.field_settings.class%
        tags:
            - { name: validator.constraint_validator, alias: ezrepoforms.validator.field_settings }

    ezrepoforms.validator.default_field_value:
        parent: ezrepoforms.validator.field_type.abstract
        class: %ezrepoforms.validator.default_field_value.class%
        tags:
            - { name: validator.constraint_validator, alias: ezrepoforms.validator.default_field_value }

    ezrepoforms.twig.field_edit_rendering_extension:
        class: %ezrepoforms.twig.field_edit_rendering_extension.class%
        arguments: [@ezpublish.templating.field_block_renderer]
        tags:
            - { name: twig.extension }

    ezrepoforms.action_dispatcher.base:
        class: EzSystems\RepositoryForms\Form\ActionDispatcher\AbstractActionDispatcher
        abstract: true
        calls:
            - [setEventDispatcher, [@event_dispatcher]]

    ezrepoforms.action_dispatcher.content_type:
        class: %ezrepoforms.action_dispatcher.content_type.class%
        parent: ezrepoforms.action_dispatcher.base

    ezrepoforms.form_processor.content_type:
        class: %ezrepoforms.form_processor.content_type.class%
        arguments: [@ezpublish.api.service.content_type, @router, %ezrepoforms.form_processor.content_type.options%]
        tags:
            - { name: kernel.event_subscriber }
