EzSystems\RepositoryForms\Data\ContentTypeData:
    constraints:
        - EzSystems\RepositoryForms\Validator\Constraints\UniqueContentTypeIdentifier: ~
    properties:
        identifier:
            - NotBlank: ~
            - Length:
                max: 50
            - Regex:
                pattern: "/^[[:alnum:]_]+$/"
                message: "ez.content_type.identifier.pattern"
        urlAliasSchema:
            - Length:
                max: 255
        nameSchema:
            - Length:
                max: 255
        defaultSortField:
            - Choice:
                # See eZ\Publish\API\Repository\Values\Content\Location::SORT_FIELD_*
                choices: [1, 2, 3, 4, 5, 6, 7, 8, 9]
        defaultSortOrder:
            - Choice:
                # See eZ\Publish\API\Repository\Values\Content\Location::SORT_ORDER_*
                choices: [0, 1]
        names:
            - Expression:
                expression: "value and value[this.mainLanguageCode] matches '/^.{1,255}$/'"
                message: "ez.content_type.names"
        descriptions:
            - Expression:
                expression: "!value or value[this.mainLanguageCode] matches '/^.{0,255}$/'"
                message: "ez.content_type.descriptions"
        fieldDefinitionsData:
            - Valid: ~

EzSystems\RepositoryForms\Data\FieldDefinitionData:
    constraints:
        - EzSystems\RepositoryForms\Validator\Constraints\UniqueFieldDefinitionIdentifier: ~
        - EzSystems\RepositoryForms\Validator\Constraints\ValidatorConfiguration: ~
        - EzSystems\RepositoryForms\Validator\Constraints\FieldSettings: ~
        - EzSystems\RepositoryForms\Validator\Constraints\FieldDefinitionDefaultValue: ~
    properties:
        identifier:
            - NotBlank: ~
            - Length:
                max: 50
            - Regex:
                pattern: "/^[[:alnum:]_]+$/"
                message: "ez.content_type.identifier.pattern"
        names:
            - Expression:
                expression: "value and value[this.contentTypeData.mainLanguageCode] matches '/^.{1,255}$/'"
                message: "ez.field_definition.names"
        descriptions:
            - Expression:
                expression: "!value or value[this.contentTypeData.mainLanguageCode] matches '/^.{0,255}$/'"
                message: "ez.field_definition.descriptions"
        position:
            - Type:
                type: integer

EzSystems\RepositoryForms\Data\RoleData:
    constraints:
        - EzSystems\RepositoryForms\Validator\Constraints\UniqueRoleIdentifier: ~

eZ\Publish\API\Repository\Values\Content\SectionStruct:
    constraints:
        - EzSystems\RepositoryForms\Validator\Constraints\UniqueSectionIdentifier: ~
    properties:
        identifier:
            - NotBlank: ~
            - Regex:
                pattern: "/^[[:alnum:]_]+$/"
                message: "ez.section.identifier.format"
        name:
            - NotBlank: ~

eZ\Publish\API\Repository\Values\ContentType\ContentTypeGroupStruct:
    properties:
        identifier:
            - NotBlank: ~
